Feat: Progress docs
skeletonlabs/skeleton pull request #2584
Opened 2024-04-02 15:39 UTC by Hugos68

This PR documents the Progress component for both Svelte and React.

2024-04-02 16:17 UTC, endigo9740 commented
@Hugos68 I've disabled the Vercel setting that requires authentication to generate a preview deployment. Will you push a quick change to test this out please? Just change some text, etc.

2024-04-02 20:04 UTC, endigo9740 requested changes
@Hugos68 I've tagged a few issues in the code, but here's a few additional suggestions:

- [ ] I'd suggest we make the Progress default color the neutral tone to match the native element. Though the track needs a bit of adjustment. Let me know if I can jump in and help with the cosmetics here.
- [ ] Let's add an example showing 2-3 size variations
- [ ] Let's add an example showing primary/secondary/tertiary variations
- [ ] We need documentation around using custom animations.

2024-04-02 20:04 UTC, endigo9740 commented on sites/next.skeleton.dev/src/examples/components/progress/Example.tsx
> +	return <Progress value={50} ariaLabelledby="A halfway filled progress bar" classes="w-full" />;
See the previous comment regarding `labelledBy`

2024-04-02 20:04 UTC, endigo9740 commented on sites/next.skeleton.dev/src/examples/components/progress/ExampleIndeterminate.svelte
> +<Progress value={undefined} ariaLabelledby="A halfway filled progress bar" classes="w-full"  />
See the previous comment regarding `labelledBy`

2024-04-02 20:04 UTC, endigo9740 commented on sites/next.skeleton.dev/src/examples/components/progress/ExampleIndeterminate.tsx
> +	return <Progress value={undefined} ariaLabelledby="A halfway filled progress bar" classes="w-full" />;
See the previous comment regarding `labelledBy`

2024-04-02 20:10 UTC, Hugos68 commented on sites/next.skeleton.dev/src/examples/components/progress/Example.svelte
> +<Progress value={50} ariaLabelledby="A halfway filled progress bar" classes="w-full" />
Oh right, it's labelledby, not label, thanks, ill exclude it from the examples

2024-04-02 20:11 UTC, endigo9740 requested changes

2024-04-02 20:11 UTC, endigo9740 commented on sites/next.skeleton.dev/src/examples/components/progress/Example.tsx
> +export default () => {
The React examples will need to be updated to follow this page-like structure we use in all existing component examples:

https://github.com/skeletonlabs/skeleton/blob/next/sites/next.skeleton.dev/src/examples/components/avatars/Example.tsx#L4

You can then import as follows:

```ts
import { Page as Example } from '@examples/components/avatars/Example.tsx';
import ExampleRaw from '@examples/components/avatars/Example.tsx?raw';
```

2024-04-03 18:03 UTC, Mahmoud-zino approved these changes
nicely done :ok_hand:

2024-04-03 20:16 UTC, merged