Patch: Accordion double click bug
skeletonlabs/skeleton pull request #2594
Opened 2024-04-05 18:37 UTC by Hugos68

Fixed Accordion regression with recent dep bump aswell as adds $bindable

2024-04-05 19:19 UTC, endigo9740 requested changes

2024-04-05 19:19 UTC, endigo9740 commented on packages/skeleton-svelte/src/lib/components/Accordion/Accordion.svelte
> +		if (multiple) {
This could be simplified with a ternary:

```ts
selected = multiple ? [...selected, id] : [id]
```

2024-04-05 19:19 UTC, endigo9740 commented on packages/skeleton-svelte/src/lib/components/Accordion/Accordion.svelte
> +		if (isOpen(id)) {
I'd opt for a ternary here too

2024-04-05 19:19 UTC, endigo9740 commented on packages/skeleton-svelte/src/lib/components/Accordion/AccordionItem.svelte
> +		if (open === ctx.isOpen(id)) {
Drop the brackets:

```ts
if (open === ctx.isOpen(id)) return;
```

2024-04-10 10:01 UTC, Hugos68 commented
@endigo9740 I've marked every question from the original review as resolved as they are not relevant due to the code changes. So please be sure to either extend the original review to cover the new code or start a new one.

2024-04-15 18:56 UTC, endigo9740 commented
@Hugos68 I've completed my review. I made a few more changes:

1. The React sandbox page now includes a `multiple` toggle via a checkbox - to match Svelte
2. Made a few other updates to the React sandbox test page to better match Svelte
3. Renamed `onValueChange` for better semantics to what it handles
4. Updated the React/Svelte doc site examples to implement the useState/$state patterns by default
5. A few other minor issues not worth describing here

With this you're clear to update the test cases. Once those are running I'll review and aim to merge asap!

Great work on this one!

2024-04-19 21:12 UTC, endigo9740 commented
@Hugos68

The test case have been updated, minus the integration test for clicking the second control. I was not able to get that working, if you want to take a look.

Additionally, I realized the React component was not taking in the open/closed icon from the parent to match the Svelte component. So I've refactored to include this.

Finally, I've updated the documentation pages to reflect all changes and tried to improve the information a bit.

I'd welcome a PR review if you get a chance!

2024-04-19 21:13 UTC, endigo9740 approved these changes

2024-04-20 16:27 UTC, Hugos68 commented
I've done my review. Overal the tests look great, coverage is good! I just think the *way* we are testing currently is a bit inefficient/inconsistent. I've left comments as to why.

2024-04-20 17:39 UTC, endigo9740 commented
@Hugos68 you'll have to submit the review before the comments will show for me. They'll remain in a pending state only available to you before then. Just go to the top of the File's Changed tab and tab the bit green button and choose submit with comments or whatever the option is!

2024-04-22 19:42 UTC, endigo9740 commented
@Hugos68 as discussed on Discord, I think the test feedback here is good and valid. But for the sake of moving this forward, let's pull that off to a follow up issue and dedicated PR. Feel free to link straight to the feedback here, and append your additional suggestions for optimizing the tests.

Technically several other React components need test cases added or updated, so I might suggest this be grouped into that larger issue. I won't have time to return to this until around mid-week, so I'd appreciate your help with any portion of this!

In the meantime, I'm going to merge the current progress so the changes are reflected on the doc site! Thanks for all the hard work on this one!

2024-04-22 19:42 UTC, merged