Bugfix: Remove nested form from InputChips
skeletonlabs/skeleton pull request #2715
Opened 2024-06-07 18:19 UTC by endigo9740

## Linked Issue

Closes #2711

## Description

This replaces the nested form used to capture mobile `Enter` keys with a `on:keyup` event handler.

NOTE: this will need to be tested heavily in the world world before we can consider merging, as it has the potential to be a breaking change.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [ ] This PR targets the `dev` branch (NEVER `master`)
- [ ] Documentation reflects all relevant changes
- [ ] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [ ] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [ ] Ensure Prettier linting is current - run `pnpm format`
- [ ] All test cases are passing - run `pnpm test`
- [ ] Includes a changeset (if relevant; see above)

2024-06-07 18:47 UTC, Hugos68 requested changes

2024-06-07 18:47 UTC, Hugos68 commented on packages/skeleton/src/lib/components/InputChip/InputChip.svelte
> +	function onKeyUpHandler(event: KeyboardEvent): void {
Change to `onKeyDownHandler`

2024-06-07 18:47 UTC, Hugos68 commented on packages/skeleton/src/lib/components/InputChip/InputChip.svelte
> +			event.stopPropagation();
You can remove this line

2024-06-07 18:47 UTC, Hugos68 commented on packages/skeleton/src/lib/components/InputChip/InputChip.svelte
> +			on:keyup={onKeyUpHandler}
Change to `on:keydown`

2024-06-07 18:47 UTC, Hugos68 commented on packages/skeleton/src/lib/components/InputChip/InputChip.svelte
> +		if (event.key === 'Enter') {
Bit of a nitpick, but I would just use and early return: `if (event.key !== 'Enter') return`

2024-06-07 19:04 UTC, Hugos68 approved these changes

2024-06-07 23:59 UTC, multiwebinc commented
Are the changes to all the `pnpm-lock` files necessary for this PR?

2024-06-08 07:46 UTC, niktek commented
> Are the changes to all the `pnpm-lock` files necessary for this PR?

Could they have been in a separate PR, yes, but they aren't unexpected either as they are a result of updating to pnpm v9

2024-06-08 17:01 UTC, endigo9740 commented
Yeah sorry about that. I work on multiple projects and recently needed to update PNPM for one of those. This was just a side effect.

2024-06-09 00:14 UTC, merged