Call custom event handlers
skeletonlabs/skeleton pull request #3073
Opened 2024-12-19 23:12 UTC by phamduylong

## Linked Issue

Closes #3064

## Description

Call zagProps events whenever applicable

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

2024-12-20 17:42 UTC, Hugos68 requested changes
For the `Pagination` component, the reason the callback in conjunction with binding doesn't work is because the callbacks *need* to be defined at the `context` level. Not the machine level.
This makes it work:
```diff
const [snapshot, send] = useMachine(
		pagination.machine({
			id: useId(),
			count: data.length,
-			onPageChange(details) {
-				zagProps.onPageChange?.(details);
-				page = details.page;
-			},
-			onPageSizeChange(details) {
-				zagProps.onPageSizeChange?.(details);
-				pageSize = details.pageSize;
-			}
		}),
		{
			context: {
				...zagProps,
+			        onPageChange(details) {
+				        zagProps.onPageChange?.(details);
+				        page = details.page;
+			        },
+			        onPageSizeChange(details) {
+				        zagProps.onPageSizeChange?.(details);
+				       pageSize = details.pageSize;
+			        },
				get page() {
					return page;
				},
				get pageSize() {
					return pageSize;
				},
				get count() {
					// Use 'count' if specified; required for server-side pagination.
					return zagProps.count ?? data.length;
				}
			}
		}
	);
```
Apart from that, LGTM!

2024-12-28 00:34 UTC, phamduylong commented
Browsing through Zag's source code for Pagination, it seems like the `onPageChange` event is only being triggered because they handle an onclick event internally for it. `onPageSizeChange` on the other hand doesn't have anything similar.
[Source](https://github.com/chakra-ui/zag/blob/9ca9b9edd448071351271465629024ecb1eb80be/packages/machines/pagination/src/pagination.connect.ts#L89)

2025-01-09 17:24 UTC, endigo9740 commented
@phamduylong @Hugos68 just checking on the status of this guys. Looks like Hugo suggested a change, but no change was made before this was flagged for review again. Hugo can you confirm Long's response and indicate if there's any further action needed here.

2025-01-09 17:32 UTC, Hugos68 commented
@endigo9740 Yeah the change is still needed, otherwise it will contain a bug

2025-01-09 20:57 UTC, phamduylong commented
@endigo9740 @Hugos68 See [discussion happened on Discord](https://discord.com/channels/1003691521280856084/1191790107867488316/1319741569540030464)

At least the suggested change doesn't work so there needs to be something else. I tried an effect rune call to make it work but this is not something I'd like to commit, it's just quite ugly.

```js
$effect(() => {
    zagProps.onPageSizeChange?.({ pageSize });
});
```

Hugo if you meant something else, could you elaborate? I couldn't make this work in any sense.

2025-01-24 17:11 UTC, closed without merging